version: '3.8'
services:
  db:
    image: postgres:16.3
    container_name: take_my_money_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
volumes:
  postgres_data: {}
networks:
  default:
    name: myapp_default
